### ISSUE TITLE
make is failing when testing flake8

### ISSUE THREAD

**Issue by d2-d2** [LINKIWI/modern-paste#14] opened 2016-05-10 19:38 UTC
This is really strange. I'm running your code in sandboxed environment (debootstrap+mounted /proc, /sys and /dev/pty). Make command is failing with following info when /proc is mounted:

```
[...]
Flake8...................................................................................................................................................Failed
hookid: flake8

Traceback (most recent call last):
  File "/root/.pre-commit/repo4ONspc/py_env-default/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/root/.pre-commit/repo4ONspc/py_env-default/local/lib/python2.7/site-packages/flake8/main.py", line 25, in main
    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
  File "/root/.pre-commit/repo4ONspc/py_env-default/local/lib/python2.7/site-packages/flake8/engine.py", line 284, in get_style_guide
    report = styleguide.init_report(reporter)
  File "/root/.pre-commit/repo4ONspc/py_env-default/local/lib/python2.7/site-packages/flake8/engine.py", line 187, in init_report
    return self._styleguide.init_report(reporter)
  File "/root/.pre-commit/repo4ONspc/py_env-default/local/lib/python2.7/site-packages/pep8.py", line 1827, in init_report
    self.options.report = (reporter or self.options.reporter)(self.options)
  File "/root/.pre-commit/repo4ONspc/py_env-default/local/lib/python2.7/site-packages/pep8.py", line 1721, in __init__
    super(StandardReport, self).__init__(options)
  File "/root/.pre-commit/repo4ONspc/py_env-default/local/lib/python2.7/site-packages/flake8/reporter.py", line 43, in __init__
    self.task_queue = multiprocessing.Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 38] Function not implemented

Fix requirements.txt.....................................................................................................................................Passed
scss_lint................................................................................................................................................Passed

```

**Comment by LINKIWI** [comment] 2016-05-11 04:02
I'm guessing this is caused by a problem in your sandbox configuration, as [this answer from SO](http://stackoverflow.com/questions/6033599/oserror-38-errno-38-with-multiprocessing) would suggest. I don't believe there's much I can do on my side of things, as all the pre-commit hooks are externally sourced. Could you try the answer proposed in the SO question and report back with results?

**Comment by LINKIWI** [comment] 2016-06-03 22:47
Closing this for now; please reopen if this issue is still not resolved or if this problem comes up again.

**Closed by LINKIWI** 2016-06-03 22:47 UTC
