### ISSUE TITLE
Non Latin symbols are not displayed properly.

### ISSUE THREAD

**Issue by rr40** [LINKIWI/modern-paste#24] opened 2016-09-26 16:30 UTC
So here's a huge problem with his beautiful software.

I'm trying to paste Cyrillic text on my Mac from Sublime Text, encoded in UTF-8. As a result I'm getting just "????" marks instead of normal symbols. 

![screen shot 2016-09-26 at 19 29 19](https://cloud.githubusercontent.com/assets/12167904/18842963/ee402cca-8427-11e6-93b5-a16f465a87a0.png)

![screen shot 2016-09-26 at 19 29 46](https://cloud.githubusercontent.com/assets/12167904/18842981/fe6bae26-8427-11e6-8e22-fe631df43da8.png)

**Comment by LINKIWI** [comment] 2016-09-27 13:33
Thanks for the report--I'm able to repro and it looks like this problem is related to character encoding in the database schema. I'll investigate.

```
Warning: Incorrect string value: '\xEB\xB6\x90\xEB\xB0\x94...' for column 'contents' at row 1
  cursor.execute(statement, parameters)
```

**Comment by LINKIWI** [comment] 2016-09-27 13:48
A quick patch you can apply to fix the issue is altering the schema directly.

```
mysql> ALTER TABLE modern_paste.paste MODIFY COLUMN contents TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

Please make sure you are on MySQL >=5.5.3 for `utf8mb4` support. I believe the connection charset defaults to utf8mb4 on this version onwards; if not, you will need to append `?charset=utf8mb4` to the end of the `SQLALCHEMY_DATABASE_URI` connection URI in `flask_config.py`.

In the meanwhile I will look into making a the column default to `utf8mb4` as part of the table creation process.

**Comment by rr40** [comment] 2016-09-27 16:57
Thanks for your swift answer. I will silently wait for a patch =)

**Comment by LINKIWI** [comment] 2016-09-27 23:59
Can you try pulling in 52895a2f74af872951984033c68b33d5ed593423 (on the `dev` branch) to see if this resolves the issue? You will need to recreate the database:

```bash
$ cd /path/to/modern-paste
$ # update to the above sha
$ export PYTHONPATH=$(pwd)/app
$ python build/build_database.py --drop
$ python build/build_database.py --create
```

**Comment by rr40** [comment] 2016-09-28 08:41
The problem is that I discovered this bug using your demo version and so far there's no active installation on my own server.

**Comment by LINKIWI** [comment] 2016-09-28 13:14
I've deployed the fix to the [demo version](https://demo.modernpaste.com/); it seems that the issue is resolved. I'll close this issue for now as resolved, but feel free to re-open if you still see problems.

**Closed** 2016-09-28 13:15 UTC
Labels: bug
